package it.water.shared.entity.api;

import it.water.core.api.repository.BaseRepository;
import it.water.shared.entity.model.WaterSharedEntity;

import java.util.List;

/**
 * @Generated by Water Generator
 * Interface component for SharedEntity Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 */
public interface SharedEntityRepository extends BaseRepository<WaterSharedEntity> {
    WaterSharedEntity findByPK(String entityResourceName, long entityId, long userId);

    void removeByPK(String entityResourceName, long entityId, long userId);

    List<WaterSharedEntity> findByEntity(String entityResourceName, long entityId);

    List<WaterSharedEntity> findByUser(long userId);

    List<Long> getSharingUsers(String entityResourceName, long entityId);

    List<Long> getEntityIdsSharedWithUser(String entityResourceName, long userId);
}
