package it.water.shared.entity.api;

import it.water.core.api.service.BaseEntityApi;
import it.water.shared.entity.model.WaterSharedEntity;

import java.util.List;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 */
public interface SharedEntityApi extends BaseEntityApi<WaterSharedEntity> {
    WaterSharedEntity findByPK(String entityResourceName, long entityId, long userId);

    void removeByPK(WaterSharedEntity entity);

    List<WaterSharedEntity> findByEntity(String entityResourceName, long entityId);

    List<WaterSharedEntity> findByUser(long userId);

    List<Long> getSharingUsers(String entityResourceName, long entityId);

    List<Long> getEntityIdsSharedWithUser(String entityResourceName, long userId);
}